### ISSUE TITLE
Merge instances of the dimensionless unit "one"

### ISSUE THREAD

**Issue by opoudjis** [unitsml/unitsdb#15]
There are multiple instances in units.yaml of the unit "one": they are differentiated by quantity and dimension. However, we already have units applicable to multiple quantities, so that on its own is not a reason to differentiate units. As for the dimensions, they are all anonymous dimensionless dimensions: 

````
NISTd80:
  dimensionless: true

...

NISTd95:
  dimensionless: true
````

I strongly recommend that the instances of "one" be merged.

See https://en.wikipedia.org/wiki/Parts-per_notation#Uno

The SI Brochure discusses the "one" dimensionless unit in sections 2.3.3 and 5.4.7. From that discussion, it is clear that there is only a single "one" unit (which could have been named as the Uno), although the radian and steradian are retained as distinct units for convenience, and ratios can also be expressed as Unit/Unit, e.g. mol/mol.

**Comment by ronaldtse** [comment]
UnitsDB currently contains dozens of dimensionless units that are basically orphaned.

The SI Brochure states:

2.3.3
> There are quantities Q for which the defining equation is such that all of the dimensional exponents in the equation for the dimension of Q are zero. This is true in particular for any quantity that is defined as the ratio of two quantities of the same kind. For example, the refractive index is the ratio of two speeds and the relative permittivity is the ratio of the permittivity of a dielectric medium to that of free space. Such quantities are simply numbers. The associated unit is the unit one, symbol 1, although this is rarely explicitly written (see 5.4.7).

> There are also some quantities that cannot be described in terms of the seven base quantities of the SI, but have the nature of a count. Examples are a number of molecules, a number of cellular or biomolecular entities (for example copies of a particular nucleic acid sequence), or degeneracy in quantum mechanics. Counting quantities are also quantities with the associated unit one.
> The unit one is the neutral element of any system of units – necessary and present automatically. There is no requirement to introduce it formally by decision. Therefore, a formal traceability to the SI can be established through appropriate, validated measurement procedures.

> It is especially important to have a clear description of any quantity with unit one (see section 5.4.7) that is expressed as a ratio of quantities of the same kind (for example length ratios or amount fractions) or as a count (for example number of photons or decays).

5.4.7
> As discussed in Section 2.3.3, values of quantities with unit one, are expressed simply as numbers. The unit symbol 1 or unit name “one” are not explicitly shown. SI prefix symbols can neither be attached to the symbol 1 nor to the name “one”, therefore powers of 10 are used to express particularly large or small values.
> Quantities that are ratios of quantities of the same kind (for example length ratios and amount fractions) have the option of being expressed with units (m/m, mol/mol) to aid the understanding of the quantity being expressed and also allow the use of SI prefixes, if this is desirable (μm/m, nmol/mol). Quantities relating to counting do not have this option, they are just numbers.

From @opoudjis :
> This is saying very clearly that there is only a single unit
> though they do allow radian, steradian as legacy dimensionless ratios

Thus:
* "one" is a special unit that cannot take prefixes, and there is only 1 dimensionless unit
  * => we merge all the dimensionless units into one
* quantities that are ratios of quantities of the same kind can have prefixes (this is an "option"). 
  * mol/mol is a ratio that represents a quantity that is a ratio which is dimensionless. such a quantity is technically also of the unit "one".
  * a ratio of the same kind can have prefixes e.g. umol/mol or nmol/mol
  * => it's not just a "notational variant", to show um/m or mol/mol we need to know how the number was generated, and the user must provide that if it is to be displayed that way

**Comment by opoudjis** [comment]
All instances of "one" but the last differ in dimension and quantity (because they are in fact ratios, and reference orphan dimensions).

I think we should be eliminating those orphan dimensions, and allowing "1" to be multi-quantity (as well as an option of it being nil quantity).

**Comment by ronaldtse** [comment]
> I think we should be eliminating those orphan dimensions, and allowing "1" to be multi-quantity (as well as an option of it being nil quantity).

Agree. Should we have a quantity to represent the "nil" quantity?

**Comment by opoudjis** [comment]
Yes.
