### ISSUE TITLE
Add dimension Unicode symbols

### ISSUE THREAD

**Issue by ronaldtse** [unitsml/unitsdb#31]
https://github.com/metanorma/bipm-si-brochure/issues/121

As described by Michael Stock of BIPM:

> Although the two references which you cited, ISO 80000-1 and BIPM JCGM 200:2012 do not mention anything about bolding of symbols for dimensions, it is quite unusual to use bold letters as symbols for dimensions. In fact, bold letters are usually used for matrices.
> 
> I would prefer your last table, for the reason that visually it gives the best result. In my opinion the risk that someone would copy the sans serif theta from this table and get a serif theta is acceptable.

The code points can be found here:

```adoc
[%unnumbered]
[[table3_4]]
.all "Dimensions" symbols use Latin “plain” capital characters, except theta uses Greek “normal” capital character (U+03F4)
[cols="<,<,<"]
|===
| Base quantity | Typical symbol for quantity | Symbol for dimension

| time | stem:[t] | stem:[sf "&#x1D5B3;"]
| length | stem:[l, x, r], etc. | stem:[sf "&#x1D5AB;"]
| mass | stem:[m] | stem:[sf "&#x1D5AC;"]
| electric current | stem:[ii(I), i] | stem:[sf "&#x1D5A8;"]
| thermodynamic temperature | stem:[ii(T)] | stem:[sf "&#x03F4;"]
| amount of substance | stem:[n] | stem:[sf "&#x1D5AD;"]
| luminous intensity | stem:[ii(I)_("v")] | stem:[sf "&#x1D5A9;"]
|===
```

**Comment by opoudjis** [comment]
Oops, already done independently for the same ticket.

we are doing sans serif + the Greek codepoint for MathML and LaTeX for thermodynamic temperature (and plane angle, phi, which that table leaves out), but for Unicode and HTML, we are going to use the bold sans serif single code point, as the only single-character example.

**Comment by ronaldtse** [comment]
@opoudjis just to confirm that we will be using the math sans serif codepoints for all except for Theta which would be non-math Greek. No bold codepoints are to be used as per BIPM.

**Comment by opoudjis** [comment]
That means no sans serif as the strict Unicode point. In the mathml and latex encoding I am already using the non math Greek point, and that is what is appearing in the brochure, so I don't think I need to change anything

**Comment by ronaldtse** [comment]
Thanks!
