### ISSUE TITLE
Encoding a non-italic "mu" symbol

### ISSUE THREAD

**Issue by manuelfuenmayor** [unitsml/unitsdb#46]
According to my tests, encoding a "mu" symbol using unitsml asset is invalid.
For example, doing:
```adoc
1 "unitsml(u)"
````
Won't render the "mu" symbol.

Of course, I could just do `1 mu`. But this will result in an italicized "mu" symbol.
And there are cases where a straight presentation of the symbol is required.

For example, this
````
1 mu
````

renders:
![issue1-1](https://github.com/unitsml/unitsdb/assets/33627611/d129f0d9-5a18-411a-b9c5-8b15ecd369aa)

(An italic "mu" symbol)

And this:
````
stem:[1 "unitsml(uV)"]
````

renders:
![issue1-2](https://github.com/unitsml/unitsdb/assets/33627611/3406113b-f9eb-4b03-aee5-0e99552cebb9)

(Which contains a non-italic "mu" symbol.)

Is there a way to obtain a non-italic "mu" symbol alone?

**Comment by manuelfuenmayor** [comment]
I've also tested: `1 rm(mu)`. I get the same result (italic "mu").

**Comment by opoudjis** [comment]
You're looking in the wrong place.

https://github.com/plurimath/asciimath2unitsml/blob/main/README.adoc

> Standalone prefixes can be recognised by replacing the unit with hyphen; so unitsml(p-) corresponds to the standalone prefix "pico" (and is rendered as "p").

`stem:["unitsml(u-)"]` renders in non-italic.

````
<stem type="MathML"><math xmlns="http://www.w3.org/1998/Math/MathML">
  <mstyle displaystyle="true">
    <mrow xref="NISTp10_-6"><mi mathvariant="normal">µ</mi></mrow>
  </mstyle>
</math><asciimath>"unitsml(u-)"</asciimath></stem>
````
